datadog_site: "datadoghq.eu"
datadog_config:
  logs_enabled: true

datadog_checks:
  http_check:
    init_config:

    instances:
      - name: Localhost
        url: http://localhost

redmine_db_mysql: rc1b-zhr7mbdxdom8rag6.mdb.yandexcloud.net
redmine_db_username: mcomet
redmine_db_database: db1
redmine_db_port: 3306
